apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktdf
  template:
    metadata:
      labels:
        app: oktdf
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "4035a577-978f-44d4-b765-dd43403bcc8a"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "8c5f14f5-aed6-425c-b4e8-26d39b053ed0"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
